APPLICATION = uber_button
RIOTBASE = ../RIOT/

FEATURES_REQUIRED = periph_spi

USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps
USEMODULE += xtimer
USEMODULE += nrf24l01p
USEMODULE += servo

# set default device parameters in case they are undefined
NRF_SPI_PORT ?= SPI_0
WS2812_SPI_PORT ?= SPI_1
CE_PIN   ?= GPIO_PIN\(PORT_A,6\)
CS_PIN   ?= GPIO_PIN\(PORT_E,3\)
IRQ_PIN  ?= GPIO_PIN\(PORT_A,7\)

CFLAGS_OPT = -O3 -Wno-unused
# export parameters

CFLAGS += -DENABLE_RES_LADDER=1
CFLAGS += -DRES_LADDER_ADC=ADC_0
CFLAGS += -DRES_LADDER_CHAN=2

CFLAGS += -DENABLE_LCD=1

CFLAGS += -DENABLE_WS2812=1
CFLAGS += -DWS2812_SPI_PORT=$(WS2812_SPI_PORT)

CFLAGS += -DENABLE_NRF_COMM=1
CFLAGS += -DNRF_SPI_PORT=$(NRF_SPI_PORT)
CFLAGS += -DCE_PIN=$(CE_PIN)
CFLAGS += -DCS_PIN=$(CS_PIN)
CFLAGS += -DIRQ_PIN=$(IRQ_PIN)

CFLAGS += -DENABLE_MM5450=0
CFLAGS += -DMM5450_CLK=GPIO_PIN\(PORT_C,5\)
CFLAGS += -DMM5450_DIN=GPIO_PIN\(PORT_C,4\)

CFLAGS += -DENABLE_ROTARY=1
CFLAGS += -DROTARY_PIN2=GPIO_PIN\(PORT_D,6\)
CFLAGS += -DROTARY_PIN1=GPIO_PIN\(PORT_C,7\)

CFLAGS += -DENABLE_ROTARY_BUTTON=1
CFLAGS += -DROTARY_BUTTON_PIN=GPIO_PIN\(PORT_D,7\)

CFLAGS += -DENABLE_BOARD_SWITCH=1

CFLAGS += -DENABLE_SERVO=1
CFLAGS += -DSERVO_FREQUENCY=50 -DSERVO_RESOLUTION=0xc3500
CFLAGS += -DSERVO_PWM=PWM_2
##CFLAGS += -I$(HOME)/git/ubberFrame

include $(RIOTBASE)/Makefile.include
